# Generated by Django 5.2.17 on 2026-09-09 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(help_text='Short uppercase code used as the task key prefix, e.g. SHOP.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Key must be 2-10 uppercase letters or digits and start with a letter.', regex='^[A-Z][A-Z0-9]{1,9}$')])),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DONE', 'Done'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10)),
                ('task_counter', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'joined_at'],
            },
        ),
    ]
