# Generated by Django 5.2.17 on 2026-09-13 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(help_text='Short uppercase code used as the task key prefix, e.g. SHOP.', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Key must be 2-10 letters or digits and start with a letter.', regex='^[A-Za-z][A-Za-z0-9]{1,9}$')]),
        ),
    ]
