# Generated by Django 5.2.17 on 2026-09-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_lowercase_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive types cannot be chosen for new tasks.'),
        ),
    ]
