# Generated by Django 5.2.17 on 2026-09-19 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_comments_and_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivity',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='tasks.comment'),
        ),
    ]
