# Generated by Django 5.2.17 on 2026-09-19 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskactivity_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='tasks.comment'),
        ),
    ]
