# Generated by Django 5.2.17 on 2026-09-21 21:34

import users.services.avatars
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', upload_to=users.services.avatars.avatar_upload_path),
        ),
    ]
